# Generated by Django 5.2.7 on 2025-12-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='notificar_usuarios',
            field=models.BooleanField(default=False, help_text='Marque para enviar uma notificação aos usuários interessados nesta categoria.'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='urgente',
            field=models.BooleanField(default=False, help_text='Marca a notícia como urgente e dispara a notificação na primeira vez que for ativada.', verbose_name='É Urgente?'),
        ),
    ]
