# Generated by Django 5.2.7 on 2025-12-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0002_notificacao_notificar_usuarios_alter_noticia_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='notificacao',
            field=models.BooleanField(default=False, help_text='Marque para disparar a notificação para usuários interessados (aciona no salvamento).', verbose_name='Enviar Notificação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='É Urgente?'),
        ),
    ]
